languageCode = "en-us"
title = "Yet Another Gallery"
theme = "AutoPhugo"
disableKinds = [
  "taxonomy",
  "term"
]
baseURL = "https://mipmip.github.io/hugo-theme-yaviga/"

[services]

  [services.googleAnalytics]

[params]
description = "AutoPhugo - Photo Gallery on Hugo"
keywords = "phugo, hugo, photogallery, photoblog, hugo theme"
images_downloadable = false
showBreadCrum = false

  [params.author]
  name = "John Doe"
  email = "jon@doe.com"

  [params.header]

    [[params.header.links]]
    name = "Cats"
    url = "/hugo-theme-yaviga/gallery/cats/"

    [[params.header.links]]
    name = "Video's"
    url = "/hugo-theme-yaviga/gallery/videos"

    [[params.header.links]]
    name = "About"
    url = "#footer"

  [params.footer]
  copyright2 = "c2"

    [params.footer.paragraph]
    headline = "Contact me"
    text = "This is my portfolio. Photo's and video's. Call me or send me a mail..\n\n[john@doe.com](mailto:john@doe.com) [+31 6 1234567890](tel:+3161234567890)"

    [params.footer.social]
    headline = "Follow me"

      [[params.footer.social.links]]
      label = "Twitter"
      url = "#"
      icon = "fa-twitter"

      [[params.footer.social.links]]
      label = "Facebook"
      url = "#"
      icon = "fa-facebook"

      [[params.footer.social.links]]
      label = "Instagram"
      url = "#"
      icon = "fa-instagram"

      [[params.footer.social.links]]
      label = "Github"
      url = "#"
      icon = "fa-github"

      [[params.footer.social.links]]
      label = "LinkedIn"
      url = "#"
      icon = "fa-linkedin"

    [params.footer.contact]
    hide = true
    formspreeID = "myuniqueID"
    headline = "Get in touch"
    buttonText = "Send"
    resetText = "Reset"

      [params.footer.contact.name]
      text = "Name *"
      warning = "Please, enter your name"

      [params.footer.contact.email]
      text = "Email *"
      warning = "Please, enter your email."

      [params.footer.contact.message]
      text = "Message *"
      warning = "Please, enter your message"

    [params.footer.copyright]
    name = "2024 - John Doe"