hugover = "extended_0.90.1"

[[serve]]
key = "default"
config = "config.toml"

[[build]]
key = "default"
config = "config.toml"

[[menu]]
key = "settings"
title = "Settings"

  [[menu.menuItems]]
  key = "mainConfig"
  [[menu.menuItems]]
  key = "galleries"

[[singles]]
key = "mainConfig"
title = "Site Configuration"
file = "config.toml"

  [[singles.fields]]
  key = "title"
  title = "Site Title"
  type = "string"
  tip = "Your page title."

  [[singles.fields]]
  key = "baseURL"
  title = "Base URL"
  type = "string"
  tip = "Your site URL."
